name: chat
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in:
  random_string:
  shared_preferences:
  top_snackbar_flutter:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true

  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
